source 'https://rubygems.org'
ruby '1.9.3'

gem 'thin'
gem 'sinatra'
gem 'httparty'
gem 'rb-libsvm'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'async_enum', github: 'aj0strow/async_enum'
gem 'tux'
gem 'newrelic_rpm'
